have_fun: false
code_review:
  disable: false
  comment_severity_threshold: HIGH  # solo comenta de HIGH+
  max_review_comments: 50
  pull_request_opened:
    help: false
    summary: true
    code_review: true
    include_drafts: true
ignore_patterns:
  - "dist/**"
  - "**/*.min.js"
  - "node_modules/**"
